logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

jjwt:
  password:
    encoder:
      secret: secret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 1800 #60 * 30